# Generated by Django 5.1.4 on 2026-08-10 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('agrochemical', 'Agrochemical'), ('tools', 'Tools & Supplies'), ('other', 'Other')], max_length=20)),
                ('unit', models.CharField(help_text="e.g. '50kg bag', '1L bottle', 'packet'", max_length=50)),
                ('price_ghs', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InputOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price_ghs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Farmer Pickup'), ('delivery', 'Delivery to Farmer')], default='pickup', max_length=10)),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('payment_channel', models.CharField(blank=True, choices=[('mtn_momo', 'MTN MoMo'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money'), ('card', 'Card (Hubtel Checkout)')], help_text="Farmer's chosen payment channel for this order", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inputs.inputproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
