# Generated by Django 5.1.4 on 2026-08-04 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=120)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=9)),
                ('photo_url', models.URLField(blank=True)),
                ('ai_grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('ungraded', 'Ungraded')], default='ungraded', max_length=10)),
                ('ai_grading_notes', models.TextField(blank=True, help_text='Explanation the AI gave for the grade assigned')),
                ('fair_price_band_low_ghs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('fair_price_band_high_ghs', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('expired', 'Expired')], default='listed', max_length=20)),
                ('listed_via', models.CharField(choices=[('app', 'App'), ('ussd', 'USSD'), ('voice', 'Voice')], default='app', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price_ghs', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.producelisting')),
            ],
        ),
    ]
