# Generated by Django 5.1.4 on 2026-08-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, help_text="Required when delivery_method is 'delivery'", max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN MoMo'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money'), ('card', 'Card (Hubtel Checkout)')], help_text="Buyer's chosen payment channel for this order", max_length=20),
        ),
        migrations.AddField(
            model_name='producelisting',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text="Payment channels this farmer accepts, e.g. ['mtn_momo', 'card']. Values from Transaction.Channel."),
        ),
        migrations.AddField(
            model_name='producelisting',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Pickup point, or the area this farmer can deliver to', max_length=255),
        ),
        migrations.AddField(
            model_name='producelisting',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup Only'), ('delivery', 'Delivery Only'), ('both', 'Pickup or Delivery')], default='pickup', max_length=10),
        ),
    ]
