# Generated by Django 5.1.4 on 2026-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_order_delivery_address_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producelisting',
            name='grading_source',
            field=models.CharField(blank=True, choices=[('ai', 'AI Graded'), ('manual', 'Farmer Graded')], help_text='Who assigned the current grade — blank until graded either way', max_length=10),
        ),
    ]
