# Generated by Django 5.1.4 on 2026-08-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_producelisting_grading_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='producelisting',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], help_text='What kind of file photo_url points at. AI grading only runs for images.', max_length=10),
        ),
    ]
