# Generated by Django 5.1.4 on 2026-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_read_notification_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text="Relative in-app path to navigate to when this notification is clicked, e.g. '/farmer/orders'.", max_length=255),
        ),
    ]
