# Generated by Django 5.1.4 on 2026-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_action_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('weather_alert', 'Weather Alert'), ('booking_update', 'Equipment Booking Update'), ('listing_update', 'Produce Listing Update'), ('payment_update', 'Payment Update'), ('crop_health_alert', 'Crop Health Alert')], max_length=30),
        ),
    ]
