# Generated by Django 5.1.4 on 2026-08-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('weather_alert', 'Weather Alert'), ('booking_update', 'Equipment Booking Update'), ('listing_update', 'Produce Listing Update'), ('payment_update', 'Payment Update'), ('crop_health_alert', 'Crop Health Alert'), ('input_order_update', 'Farm Input Order Update')], max_length=30),
        ),
    ]
