# Generated by Django 5.1.4 on 2026-08-08 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=120)),
                ('photo_url', models.URLField()),
                ('diagnosis', models.CharField(blank=True, help_text="e.g. 'Maize Streak Virus', 'Healthy'", max_length=200)),
                ('severity', models.CharField(choices=[('healthy', 'Healthy — No Disease Detected'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('unknown', 'Could Not Determine')], default='unknown', max_length=10)),
                ('symptoms_observed', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ai', 'AI Diagnosis'), ('manual', 'Manual (Admin/Extension Officer)')], default='ai', max_length=10)),
                ('needs_admin_attention', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes an admin/extension officer adds after review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
