# Generated by Django 5.1.4 on 2026-08-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbooking',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Where the equipment should be picked up from or delivered to', max_length=255),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Farmer Pickup'), ('delivery', 'Delivery to Farmer')], default='pickup', max_length=10),
        ),
        migrations.AddField(
            model_name='equipmentbooking',
            name='payment_channel',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN MoMo'), ('vodafone_cash', 'Vodafone Cash'), ('airteltigo', 'AirtelTigo Money'), ('card', 'Card (Hubtel Checkout)')], help_text="Farmer's chosen payment channel for this booking", max_length=20),
        ),
    ]
