# Generated by Django 5.1.4 on 2026-08-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentbooking_delivery_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
