# Generated by Django 5.1.4 on 2026-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo push token registered by the mobile app, if any.', max_length=200),
        ),
    ]
