# Generated by Django 5.1.4 on 2026-08-10 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_expo_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('dealer', 'Equipment Dealer'), ('input_dealer', 'Input Dealer'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
        migrations.CreateModel(
            name='InputDealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('agrochemicals', 'Agrochemicals'), ('tools', 'Tools & Equipment Supplies'), ('general', 'General Agro-Input Store')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
