from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from .models import PlantingRecommendation, WeatherForecast
from .serializers import PlantingRecommendationSerializer, WeatherForecastSerializer


class WeatherForecastViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = WeatherForecast.objects.all().order_by("-forecast_date")
    serializer_class = WeatherForecastSerializer
    permission_classes = [IsAuthenticated]
    filterset_fields = ["community", "district"]


class PlantingRecommendationViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Recommendations are generated by the AI pipeline (see services.py), not
    written directly via the API — hence read-only here. Farmers only ever
    see their own; admins see everything.
    """

    queryset = PlantingRecommendation.objects.all()
    serializer_class = PlantingRecommendationSerializer
    permission_classes = [IsAuthenticated]
    filterset_fields = ["farmer", "crop", "recommended_action"]

    def get_queryset(self):
        user = self.request.user
        qs = PlantingRecommendation.objects.select_related("farmer")
        if user.role == "admin" or user.is_staff:
            return qs
        return qs.filter(farmer=user)
