# Generated by Django 5.1.4 on 2026-08-04 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(max_length=120)),
                ('district', models.CharField(default='Tamale Metro', max_length=120)),
                ('forecast_date', models.DateField()),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_high_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_low_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_provider_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['community', 'forecast_date'], name='weather_wea_communi_370404_idx')],
                'unique_together': {('community', 'forecast_date')},
            },
        ),
        migrations.CreateModel(
            name='PlantingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=120)),
                ('recommended_action', models.CharField(choices=[('plant', 'Plant'), ('harvest', 'Harvest'), ('request_equipment', 'Request Equipment'), ('hold', 'Hold / Wait')], max_length=30)),
                ('recommended_window_start', models.DateField()),
                ('recommended_window_end', models.DateField()),
                ('ai_rationale', models.TextField(help_text='Plain-language explanation surfaced to the farmer, incl. voice/USSD')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_recommendations', to=settings.AUTH_USER_MODEL)),
                ('based_on_forecast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='weather.weatherforecast')),
            ],
        ),
    ]
